name: Run acceptance tests

on: workflow_call

jobs:
  static-site:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        node-version: [18.x, 19.x]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./playground/static-site
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - uses: actions/download-artifact@v3
        with:
          name: build-output
          path: packages/pages/dist

      # It's important to not run the build for @yext/pages on Windows.
      # Currently the build does not work (on Windows) and will replace the
      # downloaded build artifact without any warnings/errors.
      - run: pnpm i --ignore-scripts
      - run: ls ./node_modules/@yext/pages/dist/bin

      - name: Ensure dev mode works
        run: |
          pnpm run dev &
          npx wait-on -t 5000 http://localhost:5173 &&
          npx wait-on -t 1000 http://localhost:5173/index.html
      - name: Ensure build doesn't error
        run: pnpm run build-test-site
