name: Build and Test (Yext Sites Scripts)

on:
  push:
    branches-ignore:
      - "main"
    paths:
      - "packages/yext-sites-scripts/**"

jobs:
  call_build:
    uses: ./.github/workflows/build.yml
    with:
      package: "yext-sites-scripts"

  call_unit_test:
    needs: call_build
    uses: ./.github/workflows/unit_test.yml
    with:
      package: "yext-sites-scripts"
