name: Build and Test (Yext Sites Scripts)

on:
  push:
    paths: ["packages/yext-sites-scripts/**"]
    branches-ignore:
      - main

jobs:
  call_build:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/workflows/build.yml
        with:
          package: "yext-sites-scripts"

  call_unit_test:
    runs-on: ubuntu-latest
    needs: call_build

    steps:
      - uses: ./.github/workflows/unit_test.yml
        with:
          package: "yext-sites-scripts"