name: Generate markdown files

on: push 

jobs: 
  generate: 
    runs-on: ubuntu-latest
    steps:    
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
      - name: Install deps
        run: pnpm i
      - name: generate-docs
        run: pnpm run docs
      - name: Auto Generate Markdown Files
        id: generate-markdown
        uses: EndBug/add-and-commit@v9
        with:
          message: "Auto generate markdown files and push"
          add: "*"
          push: true
          pull: --rebase --autostash
          default_author: github_actions
      - name: Fail on push
        run: |
          if [[ ${{ steps.generate-markdown.outputs.pushed }} == true ]]; then exit 1; else exit 0; fi