name: Prettier Format
on:
  pull_request:
    branches: [main]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: "17.x"

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.2
      
      - name: Install deps
        run: pnpm i
      
      - name: Format code
        run: pnpm run fmt

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[format-bot] apply prettier formatting changes"
          branch: ${{ github.head_ref }}
